[tool.poetry]
name = "manim-motion-design"
version = "0.1.0"
description = ""
authors = ["RCJacH <RCJacH@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
manim = "^0.18.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
